[project]
name = "class-4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.6.0",
    "decouple>=0.0.7",
    "openai-agents>=0.1.0",
]
